apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: natinael/backnd-web-2
        ports:
        - containerPort: 5000
        env:
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: token_secret
              key: ACCESS_TOKEN_SECRET
        - name: MONGODB_URL
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
